apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-build
  labels:
    app: new-build
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-build
  template:
    metadata:
      labels:
        app: new-build
    spec:
      containers:
      - name: new-build
        image: chandans12/new-build
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: new-build-service
  labels:
    app: new-build
spec:
  selector:
    app: new-build
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
