apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-flask
  labels:
    app: project-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-flask
  template:
    metadata:
      labels:
        app: project-flask
    spec:
      containers:
      - name: project-flask
        image: chandans12/project-flask
        ports:
        - containerPort: 5050
        env:
        - name: FLASK_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: project-flask-service
  labels:
    app: project-flask
spec:
  selector:
    app: project-flask
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5050
  type: LoadBalancer